<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>Shisui.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.4.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shisui.Core\Shisui.Core.csproj" />
    <ProjectReference Include="..\Shisui.UI\Shisui.UI.csproj" />
  </ItemGroup>

</Project>
